### ISSUE TITLE
Edit Event disappears the event from the timeline

### ISSUE THREAD

**Issue by sheend** [sheend/blast#69]
Even if you don't make any changes, editing an event changes the time of the event in firebase to negative and it never shows up in the timeline

**Comment by carsonus** [comment]
The event comes in prefilled with the right date, but maybe our nice looking date string is wrong/not being read at all?

**Comment by mkhuat** [comment]
This was definitely not the case when we initially implemented the Edit
Event....

I think the formatting may have changed the original code, so I'll look at
it

**Comment by mkhuat** [comment]
dudes this was actually a pretty gross bug....

Context: we call "AddEvent" method to Create a new event and ALSO to edit a new event.

Bug: the AddEvent method uses whatever Date/Time was actively set during the duration of the activity. HOWEVER, when we edit an event and don't actively set the date/time (i.e. don't touch the time and date pickers), then the AddEvent method doesn't add the correct _unchanged_ date/time to the DB, but actually uninitialized values of "0". Lines 698-716 on FIREBASE BRANCH should fix this bug.

Thanks for pointing it out. I think we thought the time was initially being filtered out after we edited the event...... crisis averted? pls check...

**Comment by sheend** [comment]
Wowz good job friend for finding the bug

**Comment by sheend** [comment]
We still have an issue because the previous location's address and lat/long and overridden on edit save

**Comment by sheend** [comment]
So the time no longer goes to negative, but it still changes even if you dont click anything

If you look at the event time before and after clicking save, the time changed even though nothing was clicked in the time area to change it. I put those milliseconds into a converter that changes it to a readable date, and from what I can tell the edit pushes it back by either 3 or 12 hours?

<img width="1280" alt="screen shot 2016-03-05 at 7 58 56 am" src="https://cloud.githubusercontent.com/assets/6439580/13548629/990d1b98-e2a9-11e5-8caf-a58eff283ab5.png">
<img width="1280" alt="screen shot 2016-03-05 at 7 59 07 am" src="https://cloud.githubusercontent.com/assets/6439580/13548630/9a27abe2-e2a9-11e5-9149-24626325a021.png">

**Comment by carsonus** [comment]
After some testing, I think it pushes it back roughly 3 hours still, even thought the prefilled time is current. Setting the time forward about 3-4 hours from what it prefills as keeps it appearing in the main activity.

**Comment by mkhuat** [comment]
can you guys pull firebase and test the date/attendee list now? it seems to work on my end

**Comment by carsonus** [comment]
Confirmed works.
